// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.12.0+8c27801dc8d42ccc00997f25c0b8f45f8d4a233e
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace _4oito6.informacoes_cliente_cadastrado
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.12.0+8c27801dc8d42ccc00997f25c0b8f45f8d4a233e")]
	public partial class Cliente : global::Avro.Specific.ISpecificRecord
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse(@"{""type"":""record"",""name"":""Cliente"",""namespace"":""_4oito6.informacoes_cliente_cadastrado"",""fields"":[{""name"":""nome"",""type"":""string""},{""name"":""documento"",""type"":""string""},{""name"":""data_nascimento"",""type"":[""string"",""null""]},{""name"":""endereco"",""type"":[""null"",{""type"":""record"",""name"":""Endereco"",""namespace"":""_4oito6.informacoes_cliente_cadastrado"",""fields"":[{""name"":""logradouro"",""type"":""string""},{""name"":""numero"",""type"":[""string"",""null""]},{""name"":""bairro"",""type"":""string""},{""name"":""cidade"",""type"":""string""},{""name"":""estado"",""type"":""string""},{""name"":""cep"",""type"":""string""}]}]},{""name"":""telefone"",""type"":[""null"",{""type"":""record"",""name"":""Telefone"",""namespace"":""_4oito6.informacoes_cliente_cadastrado"",""fields"":[{""name"":""ddd"",""type"":""string""},{""name"":""numero"",""type"":""string""}]}]},{""name"":""email"",""type"":[""string"",""null""]},{""name"":""is_ativo"",""type"":""boolean""}]}");
		private string _nome;
		private string _documento;
		private string _data_nascimento;
		private _4oito6.informacoes_cliente_cadastrado.Endereco _endereco;
		private _4oito6.informacoes_cliente_cadastrado.Telefone _telefone;
		private string _email;
		private bool _is_ativo;
		public virtual global::Avro.Schema Schema
		{
			get
			{
				return Cliente._SCHEMA;
			}
		}
		public string nome
		{
			get
			{
				return this._nome;
			}
			set
			{
				this._nome = value;
			}
		}
		public string documento
		{
			get
			{
				return this._documento;
			}
			set
			{
				this._documento = value;
			}
		}
		public string data_nascimento
		{
			get
			{
				return this._data_nascimento;
			}
			set
			{
				this._data_nascimento = value;
			}
		}
		public _4oito6.informacoes_cliente_cadastrado.Endereco endereco
		{
			get
			{
				return this._endereco;
			}
			set
			{
				this._endereco = value;
			}
		}
		public _4oito6.informacoes_cliente_cadastrado.Telefone telefone
		{
			get
			{
				return this._telefone;
			}
			set
			{
				this._telefone = value;
			}
		}
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				this._email = value;
			}
		}
		public bool is_ativo
		{
			get
			{
				return this._is_ativo;
			}
			set
			{
				this._is_ativo = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.nome;
			case 1: return this.documento;
			case 2: return this.data_nascimento;
			case 3: return this.endereco;
			case 4: return this.telefone;
			case 5: return this.email;
			case 6: return this.is_ativo;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.nome = (System.String)fieldValue; break;
			case 1: this.documento = (System.String)fieldValue; break;
			case 2: this.data_nascimento = (System.String)fieldValue; break;
			case 3: this.endereco = (_4oito6.informacoes_cliente_cadastrado.Endereco)fieldValue; break;
			case 4: this.telefone = (_4oito6.informacoes_cliente_cadastrado.Telefone)fieldValue; break;
			case 5: this.email = (System.String)fieldValue; break;
			case 6: this.is_ativo = (System.Boolean)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
