// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.12.0+8c27801dc8d42ccc00997f25c0b8f45f8d4a233e
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace _4oito6.informacoes_cliente_cadastrado
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.12.0+8c27801dc8d42ccc00997f25c0b8f45f8d4a233e")]
	public partial class InformacoesClienteCadastrado : global::Avro.Specific.ISpecificRecord
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse(@"{""type"":""record"",""name"":""InformacoesClienteCadastrado"",""namespace"":""_4oito6.informacoes_cliente_cadastrado"",""fields"":[{""name"":""data"",""type"":{""type"":""record"",""name"":""Cliente"",""namespace"":""_4oito6.informacoes_cliente_cadastrado"",""fields"":[{""name"":""nome"",""type"":""string""},{""name"":""documento"",""type"":""string""},{""name"":""data_nascimento"",""type"":[""string"",""null""]},{""name"":""endereco"",""type"":[""null"",{""type"":""record"",""name"":""Endereco"",""namespace"":""_4oito6.informacoes_cliente_cadastrado"",""fields"":[{""name"":""logradouro"",""type"":""string""},{""name"":""numero"",""type"":[""string"",""null""]},{""name"":""bairro"",""type"":""string""},{""name"":""cidade"",""type"":""string""},{""name"":""estado"",""type"":""string""},{""name"":""cep"",""type"":""string""}]}]},{""name"":""telefone"",""type"":[""null"",{""type"":""record"",""name"":""Telefone"",""namespace"":""_4oito6.informacoes_cliente_cadastrado"",""fields"":[{""name"":""ddd"",""type"":""string""},{""name"":""numero"",""type"":""string""}]}]},{""name"":""email"",""type"":[""string"",""null""]},{""name"":""is_ativo"",""type"":""boolean""}]}}]}");
		private _4oito6.informacoes_cliente_cadastrado.Cliente _data;
		public virtual global::Avro.Schema Schema
		{
			get
			{
				return InformacoesClienteCadastrado._SCHEMA;
			}
		}
		public _4oito6.informacoes_cliente_cadastrado.Cliente data
		{
			get
			{
				return this._data;
			}
			set
			{
				this._data = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.data;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.data = (_4oito6.informacoes_cliente_cadastrado.Cliente)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
