// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.12.0+8c27801dc8d42ccc00997f25c0b8f45f8d4a233e
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace _4oito6.informacoes_cliente_cadastrado
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.12.0+8c27801dc8d42ccc00997f25c0b8f45f8d4a233e")]
	public partial class Telefone : global::Avro.Specific.ISpecificRecord
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"Telefone\",\"namespace\":\"_4oito6.informacoes_cliente_cadas" +
				"trado\",\"fields\":[{\"name\":\"ddd\",\"type\":\"string\"},{\"name\":\"numero\",\"type\":\"string\"" +
				"}]}");
		private string _ddd;
		private string _numero;
		public virtual global::Avro.Schema Schema
		{
			get
			{
				return Telefone._SCHEMA;
			}
		}
		public string ddd
		{
			get
			{
				return this._ddd;
			}
			set
			{
				this._ddd = value;
			}
		}
		public string numero
		{
			get
			{
				return this._numero;
			}
			set
			{
				this._numero = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.ddd;
			case 1: return this.numero;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.ddd = (System.String)fieldValue; break;
			case 1: this.numero = (System.String)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
