# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: KafkaTest

on:
  push:
    branches: [ "master" ]

jobs:
  kafka-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    
    - name: Setup Docker Compose
      run: sudo apt-get install -y docker-compose
    
    - name: Inicializando ambiente
      run: |
        docker-compose up -d
        echo "Aguardando containers inicializarem..."
        sleep 20
        bash init.sh

    - name: Wait to run tests
      uses: jakejarvis/wait-action@master
      with:
        time: '2s'

    - name: Execução dos testes
      working-directory: ./4oito6/4oito6.Kafka
      run: |
        dotnet restore
        dotnet build --configuration Release
        dotnet test --configuration Release --no-build