# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: KafkaTest

on:
  push:
    branches: [ "master" ]

jobs:
  dotnet-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    
    - name: Setup Docker Compose
      run: sudo apt-get install -y docker-compose
    
    - name: Inicializando ambiente
      run: |
        bash init.sh
    
    - name: Execução dos testes
      working-directory: ./4oito6/4oito6.Kafka
      run: |
        dotnet restore
        dotnet build --configuration Release
  
  python-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Setup Docker Compose
      run: sudo apt-get install -y docker-compose
      
    - name: Inicializando ambiente
      run: |
        bash init.sh
    
    - name: Execução dos testes
      working-directory: ./pykafka
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        python -m unittest test_kafka.py